language: node_js
node_js:
  - "6"

branches:
  only:
    - master

install:
  - cd ai-playground && npm install

script:
  - cd ai-playground && npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  on:
    branch: master